server:
    port: 8081
spring:
    application:
        name: demo
    freemarker:
        cache: false
        charset: UTF-8
        check-template-location: true
        content-type: text/html
        expose-request-attributes: true
        expose-session-attributes: true
        request-context-attribute: request
        suffix: .ftl

leaf:
    segment:
        enable: true
        url: jdbc:mysql://localhost:3306/leaf?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: root
    snowflake:
        enable: true
        address: 127.0.0.1
        port: 2181
    name: com.chsengni.leaf